version: '3.8'

services:

  server:
    image: server
    build:
      context: build
    ports:
      - 5000:5000      
    restart: unless-stopped 
    networks:
       observability:

  prometheus:
    image: prom/prometheus:v3.9.1
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
       observability:

  node-exporter:
    image: prom/node-exporter:v1.10.2
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.systemd'
      - '--collector.processes'
    restart: unless-stopped 
    networks:
       observability:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    ports:
      - 8080:8080
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/dev/disk/:/dev/disk:ro'
    devices:
      - '/dev/kmsg'
    restart: unless-stopped
    privileged: true
    networks:
       observability:

  grafana:
    image: grafana/grafana:12.3.1
    ports:
      - 3000:3000

    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/grafana-dashboards:/etc/grafana/provisioning/grafana-dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
       observability:

  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./collector/otc-config.yaml:/etc/otelcol/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
       observability:


networks:
  observability:
     name: observability

volumes:
    prometheus_data: {}
    grafana_data: {}
