version: '3.8'

services:

  go-api:
    image: go-api
    build:
      context: build/go
    ports:
      - 8081:8080
    restart: unless-stopped
    networks:
      observability:
    depends_on:
      - otel-collector
      - pyroscope
  server:
    image: server
    build:
      context: build/python
    ports:
      - 5000:5000
    restart: unless-stopped
    networks:
       observability:

  prometheus:
    image: prom/prometheus:v3.9.1
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
       observability:

  node-exporter:
    image: prom/node-exporter:v1.10.2
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.systemd'
      - '--collector.processes'
    restart: unless-stopped 
    networks:
       observability:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    ports:
      - 8080:8080
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/dev/disk/:/dev/disk:ro'
    devices:
      - '/dev/kmsg'
    restart: unless-stopped
    privileged: true
    networks:
       observability:

  grafana:
    image: grafana/grafana:12.3.1
    ports:
      - 3000:3000

    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/grafana-dashboards:/etc/grafana/provisioning/grafana-dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
       observability:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.143.0
    command:
      - "--config=/etc/otelcol/config.yaml"
      - "--feature-gates=service.profilesSupport"
    volumes:
      - ./collector/otc-config.yaml:/etc/otelcol/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      # - 4317:4317 # OTLP gRPC receiver
      # - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
       observability:
    depends_on:
      - pyroscope

####
# Tempo Tracing Backend
####

  init:
    image: busybox:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo

  memcached:
    image: memcached:1.6.40@sha256:894f7a8383cf110d7370329a50b8520792a9081115d131a6e24179e0d5e6fae5
    container_name: memcached
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m
      - MEMCACHED_THREADS=4

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./backend/tempo/tempo.yaml:/etc/tempo.yaml
      - ./backend/tempo/overrides.yaml:/etc/overrides.yaml
      - ./tempo-data:/var/tempo
    depends_on:
      - init
      - memcached
    restart: unless-stopped
    networks:
       observability:

####
# Loki Logs Backend
####
  loki:
    image: grafana/loki:3.6.1
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./backend/loki/loki.yaml:/etc/loki/loki.yaml
      - loki_data:/loki
    networks:
      observability:

####
# Mimir Metrics Backend
####

  mimir:
    image: grafana/mimir:latest
    command: -config.file=/etc/mimir/mimir.yaml
    volumes:
      - ./backend/mimir/mimir.yaml:/etc/mimir/mimir.yaml
      - mimir_data:/mimir
    networks:
      observability:

####
# Pyroscope Profiling Backend
####
  pyroscope:
    image: grafana/pyroscope:latest
    command:
      - "-self-profiling.disable-push=true"
    ports:
      - "4040:4040"
    networks:
      observability:

networks:
  observability:
     name: observability

volumes:
    prometheus_data: {}
    grafana_data: {}
    loki_data: {}
    mimir_data: {}
